spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soul?serverTimezone=Asia/Seoul
    username: root
    password: 219907
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
