spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/soul?serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
